### PR TITLE
Bypass LunarG Bot Verification

### PR DESCRIPTION
**Pull request by Root3287**
We are not bots. We're humans, using bots to get our stuff...

### CODE REVIEW

**Comment by apenngrace** [comment]
Thanks!

**Comment by apenngrace** [comment]
Trying to merge...

**Comment by apenngrace** [comment]
Thanks again!

**Comment by Root3287** [comment]
No problem!

**Comment by apenngrace** [comment]
Was there a download error that motivated the pull request?

**Comment by Root3287** [comment]
Just now saw the comment after a year now, but yes. LunarG at one time had increased traffic, but after manually downloading and getting through their human verification system. All you have to do is put ```?Human=true```.
Thanks CyberSecurity

**Pull request merged**
